function plus_recursive(a, b) {
    return a === 0 ? b : plus_recursive(a - 1, b) + 1;
}

console.log(plus_recursive(4, 5));

/*
The proces generated by each procedure in evaluating plus_recursive(4, 5) is recursive:

plus_recursive(4, 5)
-> plus_recursive(3, 5) + 1
-> plus_recursive(2, 5) + 1 + 1
-> plus_recursive(1, 5) + 1 + 1 + 1
-> plus_recursive(0, 5) + 1 + 1 + 1 + 1
-> 5 + 1 + 1 + 1 + 1
-> 9
*/


function plus_iterative(a ,b) {
    return a === 0 ? b : plus_iterative(a - 1, b + 1);
}

console.log(plus_iterative(4, 5));

/*
The proces generated by each procedure in evaluating plus_iterative(a, b) is iterative:

plus_iterative(4, 5)
-> plus_iterative(3, 6)
-> plus_iterative(2, 7)
-> plus_iterative(1, 8)
-> plus_iterative(0, 9)
-> 9
*/
