controller(
    [
    "begin_garbage_collection",
        assign("free", constant(0)),
        assign("scan", constant(0)),
        assign("old", reg("root")),
        assign("relocate_continue", label("reassign_root")),
        go_to(label("relocate_old_result_in_new")),
    "reassign_root",
        assign("root", reg("new")),
        go_to(label("gc_loop")),
    "gc_loop",
        test([op("==="), reg("scan"), reg("free")]),
        branch(label("gc_flip")),
        assign("old", [op("vector_ref"), reg("new_heads"), reg("scan")]),
        assign("relocate_continue", label("update_head")),
        go_to(label("relocate_old_result_in_new")),
    "update_head",
        perform([op("vector_set"), reg("new_heads"), reg("scan"), reg("new")]),
        assign("old", [op("vector_ref"), reg("new_tails"), reg("scan")]),
        assign("relocate_continue", label("update_tail")),
        go_to(label("relocate_old_result_in_new")),
    "update_tail",
        perform([op("vector_set"), reg("new_tails"), reg("scan"), reg("new")]),
        assign("scan", [op("+"), reg("scan"), constant(1)]),
        go_to(label("gc_loop")),
    "relocate_old_result_in_new",
        test([op("is_pointer_to_pair"), reg("old")]),
        branch(label("pair")),
        assign("new", reg("old")),
        go_to(reg("relocate_continue")),
    "pair",
        assign("oldht", [op("vector_ref"), reg("the_heads"), reg("old")]),
        test([op("is_broken_heart"), reg("oldht")]),
        branch(label("already_moved")),
        assign("new", reg("free")),
        // Update free pointer
        assign("free", [op("+"), reg("free"), constant(1)]),
        // Copy the head and tail to new memory
        perform([op("vector_set"), reg("the_heads"), reg("new"), reg("oldht")]),
        assign("oldht", [op("vector_ref"), reg("the_tails"), reg("old")]),
        perform([op("vector_set"), reg("the_tails"), reg("new"), reg("oldht")]),
        // Construct the broken heart
        perform([op("vector_set"), reg("the_heads"), reg("old"), constant("broken_heart")]),
        perform([op("vector_set"), reg("the_tails"), reg("old"), reg("new")]),
        go_to(reg("relocate_continue")),
    "already_moved",
        assign("new", [op("vector_ref"), reg("the_tails"), reg("old")]),
        go_to(reg("relocate_continue")),
    "gc_flip",
        assign("temp", reg("the_tails")),
        assign("the_tails", reg("new_tails")),
        assign("new_tails", reg("temp")),
        assign("temp", reg("the_heads")),
        assign("the_heads", reg("new_heads")),
        assign("new_heads", reg("temp")),
    "end_garbage_collection"
    ]
)
